import { UserRole } from './auth';

// ==============================================================================
// PropertyOS Granular Permissions & RBAC Matrix
// ==============================================================================

export enum Permission {
  // Organization Management
  ORGANIZATION_READ = 'organization.read',
  ORGANIZATION_UPDATE = 'organization.update',

  // Team & RBAC Management
  TEAM_READ = 'team.read',
  TEAM_INVITE = 'team.invite',
  TEAM_UPDATE = 'team.update',
  TEAM_REMOVE = 'team.remove',

  // Property Management Foundation
  PROPERTY_READ = 'property.read',
  PROPERTY_CREATE = 'property.create',
  PROPERTY_UPDATE = 'property.update',
  PROPERTY_DELETE = 'property.delete',

  // Tenant Management Foundation
  TENANT_READ = 'tenant.read',
  TENANT_CREATE = 'tenant.create',
  TENANT_UPDATE = 'tenant.update',
  TENANT_DELETE = 'tenant.delete',
  TENANT_KYC_READ = 'tenant.kyc.read',
  TENANT_KYC_UPLOAD = 'tenant.kyc.upload',
  TENANT_KYC_VERIFY = 'tenant.kyc.verify',
  TENANT_KYC_DELETE = 'tenant.kyc.delete',

  // Lease Management
  LEASE_READ = 'lease.read',
  LEASE_CREATE = 'lease.create',
  LEASE_UPDATE = 'lease.update',
  LEASE_TERMINATE = 'lease.terminate',

  // Billing & Finance Foundation (CORE-011)
  BILLING_READ = 'billing.read',
  BILLING_CREATE = 'billing.create',
  BILLING_UPDATE = 'billing.update',

  INVOICE_READ = 'invoice.read',
  INVOICE_CREATE = 'invoice.create',
  INVOICE_UPDATE = 'invoice.update',
  INVOICE_ISSUE = 'invoice.issue',
  INVOICE_VOID = 'invoice.void',

  PAYMENT_READ = 'payment.read',
  PAYMENT_CREATE = 'payment.create',
  PAYMENT_ALLOCATE = 'payment.allocate',
  PAYMENT_REFUND = 'payment.refund',

  LEDGER_READ = 'ledger.read',

  SECURITY_DEPOSIT_READ = 'security_deposit.read',
  SECURITY_DEPOSIT_UPDATE = 'security_deposit.update',

  // Maintenance & Operations Foundation (CORE-013)
  MAINTENANCE_READ = 'maintenance.read',
  MAINTENANCE_CREATE = 'maintenance.create',
  MAINTENANCE_UPDATE = 'maintenance.update',
  MAINTENANCE_ASSIGN = 'maintenance.assign',
  MAINTENANCE_COMMENT = 'maintenance.comment',
  MAINTENANCE_COMPLETE = 'maintenance.complete',
  MAINTENANCE_VERIFY = 'maintenance.verify',
  MAINTENANCE_CLOSE = 'maintenance.close',
  MAINTENANCE_CANCEL = 'maintenance.cancel',
  MAINTENANCE_MANAGE_COST = 'maintenance.manage_cost',
  MAINTENANCE_MANAGE_VENDOR = 'maintenance.manage_vendor',

  // Check-In & Onboarding Management
  CHECKIN_READ = 'checkin.read',
  CHECKIN_CREATE = 'checkin.create',
  CHECKIN_CANCEL = 'checkin.cancel',

  // Checkout & Settlement Management
  CHECKOUT_READ = 'checkout.read',
  CHECKOUT_CREATE = 'checkout.create',
  CHECKOUT_UPDATE = 'checkout.update',
  CHECKOUT_COMPLETE = 'checkout.complete',
  CHECKOUT_CANCEL = 'checkout.cancel',

  // Digital Agreement & Template Management
  AGREEMENT_READ = 'agreement.read',
  AGREEMENT_CREATE = 'agreement.create',
  AGREEMENT_UPDATE = 'agreement.update',
  AGREEMENT_GENERATE = 'agreement.generate',
  AGREEMENT_SIGN = 'agreement.sign',
  AGREEMENT_FINALIZE = 'agreement.finalize',
  AGREEMENT_CANCEL = 'agreement.cancel',

  // Agreement Template Management
  AGREEMENT_TEMPLATE_READ = 'agreement.template.read',
  AGREEMENT_TEMPLATE_CREATE = 'agreement.template.create',
  AGREEMENT_TEMPLATE_UPDATE = 'agreement.template.update',
  AGREEMENT_TEMPLATE_ARCHIVE = 'agreement.template.archive',

  // Electricity & Utilities Management (CORE-012)
  ELECTRICITY_READ = 'electricity.read',
  ELECTRICITY_CREATE = 'electricity.create',
  ELECTRICITY_UPDATE = 'electricity.update',
  ELECTRICITY_FINALIZE = 'electricity.finalize',

  // Food & Meal Management (CORE-012)
  MEAL_READ = 'meal.read',
  MEAL_CREATE = 'meal.create',
  MEAL_UPDATE = 'meal.update',
  MEAL_MANAGE_SUBSCRIPTIONS = 'meal.manage_subscriptions',
  MEAL_RECORD = 'meal.record',
  MEAL_FINALIZE = 'meal.finalize',

  // Staff & Attendance Management (CORE-017)
  STAFF_READ = 'staff.read',
  STAFF_CREATE = 'staff.create',
  STAFF_UPDATE = 'staff.update',
  STAFF_DELETE = 'staff.delete',
  ATTENDANCE_READ = 'attendance.read',
  ATTENDANCE_RECORD = 'attendance.record',
  ATTENDANCE_UPDATE = 'attendance.update',

  // Visitor & Gatepass Management (CORE-018)
  VISITOR_READ = 'visitor.read',
  VISITOR_CREATE = 'visitor.create',
  VISITOR_UPDATE = 'visitor.update',
  VISITOR_DELETE = 'visitor.delete',

  // Property & Room Inventory Tracking (CORE-019)
  INVENTORY_READ = 'inventory.read',
  INVENTORY_CREATE = 'inventory.create',
  INVENTORY_UPDATE = 'inventory.update',
  INVENTORY_DELETE = 'inventory.delete',

  // Expense Management (CORE-020)
  EXPENSE_READ = 'expense.read',
  EXPENSE_CREATE = 'expense.create',
  EXPENSE_UPDATE = 'expense.update',
  EXPENSE_DELETE = 'expense.delete',

  // Reporting & Analytics Foundation (CORE-021)
  REPORTS_READ = 'reports.read',

  // Dashboard Foundation (CORE-022)
  DASHBOARD_READ = 'dashboard.read',

  // In-App Notification System (CORE-023)
  NOTIFICATION_READ = 'notification.read',
  NOTIFICATION_CREATE = 'notification.create',
  NOTIFICATION_UPDATE = 'notification.update',
  NOTIFICATION_DELETE = 'notification.delete',
}

/**
 * Deterministic, Machine-Readable Role-to-Permission Mapping Matrix
 */
export const ROLE_PERMISSIONS_MAP: Record<UserRole, readonly Permission[]> = {
  [UserRole.OWNER]: [
    Permission.EXPENSE_READ,
    Permission.EXPENSE_CREATE,
    Permission.EXPENSE_UPDATE,
    Permission.EXPENSE_DELETE,
    Permission.INVENTORY_READ,
    Permission.INVENTORY_CREATE,
    Permission.INVENTORY_UPDATE,
    Permission.INVENTORY_DELETE,
    Permission.STAFF_READ,
    Permission.STAFF_CREATE,
    Permission.STAFF_UPDATE,
    Permission.STAFF_DELETE,
    Permission.ATTENDANCE_READ,
    Permission.ATTENDANCE_RECORD,
    Permission.ATTENDANCE_UPDATE,
    Permission.VISITOR_READ,
    Permission.VISITOR_CREATE,
    Permission.VISITOR_UPDATE,
    Permission.VISITOR_DELETE,
    Permission.ORGANIZATION_READ,
    Permission.ORGANIZATION_UPDATE,
    Permission.TEAM_READ,
    Permission.TEAM_INVITE,
    Permission.TEAM_UPDATE,
    Permission.TEAM_REMOVE,
    Permission.PROPERTY_READ,
    Permission.PROPERTY_CREATE,
    Permission.PROPERTY_UPDATE,
    Permission.PROPERTY_DELETE,
    Permission.TENANT_READ,
    Permission.TENANT_CREATE,
    Permission.TENANT_UPDATE,
    Permission.TENANT_DELETE,
    Permission.TENANT_KYC_READ,
    Permission.TENANT_KYC_UPLOAD,
    Permission.TENANT_KYC_VERIFY,
    Permission.TENANT_KYC_DELETE,
    Permission.LEASE_READ,
    Permission.LEASE_CREATE,
    Permission.LEASE_UPDATE,
    Permission.LEASE_TERMINATE,
    Permission.CHECKIN_READ,
    Permission.CHECKIN_CREATE,
    Permission.CHECKIN_CANCEL,
    Permission.CHECKOUT_READ,
    Permission.CHECKOUT_CREATE,
    Permission.CHECKOUT_UPDATE,
    Permission.CHECKOUT_COMPLETE,
    Permission.CHECKOUT_CANCEL,
    Permission.AGREEMENT_READ,
    Permission.AGREEMENT_CREATE,
    Permission.AGREEMENT_UPDATE,
    Permission.AGREEMENT_GENERATE,
    Permission.AGREEMENT_SIGN,
    Permission.AGREEMENT_FINALIZE,
    Permission.AGREEMENT_CANCEL,
    Permission.AGREEMENT_TEMPLATE_READ,
    Permission.AGREEMENT_TEMPLATE_CREATE,
    Permission.AGREEMENT_TEMPLATE_UPDATE,
    Permission.AGREEMENT_TEMPLATE_ARCHIVE,
    Permission.ELECTRICITY_READ,
    Permission.ELECTRICITY_CREATE,
    Permission.ELECTRICITY_UPDATE,
    Permission.ELECTRICITY_FINALIZE,
    Permission.MEAL_READ,
    Permission.MEAL_CREATE,
    Permission.MEAL_UPDATE,
    Permission.MEAL_MANAGE_SUBSCRIPTIONS,
    Permission.MEAL_RECORD,
    Permission.MEAL_FINALIZE,
    Permission.BILLING_READ,
    Permission.BILLING_CREATE,
    Permission.BILLING_UPDATE,
    Permission.INVOICE_READ,
    Permission.INVOICE_CREATE,
    Permission.INVOICE_UPDATE,
    Permission.INVOICE_ISSUE,
    Permission.INVOICE_VOID,
    Permission.PAYMENT_READ,
    Permission.PAYMENT_CREATE,
    Permission.PAYMENT_ALLOCATE,
    Permission.PAYMENT_REFUND,
    Permission.LEDGER_READ,
    Permission.SECURITY_DEPOSIT_READ,
    Permission.SECURITY_DEPOSIT_UPDATE,
    Permission.MAINTENANCE_READ,
    Permission.MAINTENANCE_CREATE,
    Permission.MAINTENANCE_UPDATE,
    Permission.MAINTENANCE_ASSIGN,
    Permission.MAINTENANCE_COMMENT,
    Permission.MAINTENANCE_COMPLETE,
    Permission.MAINTENANCE_VERIFY,
    Permission.MAINTENANCE_CLOSE,
    Permission.MAINTENANCE_CANCEL,
    Permission.MAINTENANCE_MANAGE_COST,
    Permission.MAINTENANCE_MANAGE_VENDOR,
    Permission.REPORTS_READ,
    Permission.DASHBOARD_READ,
    Permission.NOTIFICATION_READ,
    Permission.NOTIFICATION_CREATE,
    Permission.NOTIFICATION_UPDATE,
    Permission.NOTIFICATION_DELETE,
  ],

  [UserRole.PROPERTY_MANAGER]: [
    Permission.EXPENSE_READ,
    Permission.EXPENSE_CREATE,
    Permission.EXPENSE_UPDATE,
    Permission.EXPENSE_DELETE,
    Permission.INVENTORY_READ,
    Permission.INVENTORY_CREATE,
    Permission.INVENTORY_UPDATE,
    Permission.INVENTORY_DELETE,
    Permission.STAFF_READ,
    Permission.STAFF_CREATE,
    Permission.STAFF_UPDATE,
    Permission.STAFF_DELETE,
    Permission.ATTENDANCE_READ,
    Permission.ATTENDANCE_RECORD,
    Permission.ATTENDANCE_UPDATE,
    Permission.VISITOR_READ,
    Permission.VISITOR_CREATE,
    Permission.VISITOR_UPDATE,
    Permission.VISITOR_DELETE,
    Permission.ORGANIZATION_READ,
    Permission.TEAM_READ,
    Permission.PROPERTY_READ,
    Permission.PROPERTY_CREATE,
    Permission.PROPERTY_UPDATE,
    Permission.TENANT_READ,
    Permission.TENANT_CREATE,
    Permission.TENANT_UPDATE,
    Permission.TENANT_KYC_READ,
    Permission.TENANT_KYC_UPLOAD,
    Permission.TENANT_KYC_VERIFY,
    Permission.LEASE_READ,
    Permission.LEASE_CREATE,
    Permission.LEASE_UPDATE,
    Permission.LEASE_TERMINATE,
    Permission.CHECKIN_READ,
    Permission.CHECKIN_CREATE,
    Permission.CHECKIN_CANCEL,
    Permission.CHECKOUT_READ,
    Permission.CHECKOUT_CREATE,
    Permission.CHECKOUT_UPDATE,
    Permission.CHECKOUT_COMPLETE,
    Permission.CHECKOUT_CANCEL,
    Permission.AGREEMENT_READ,
    Permission.AGREEMENT_CREATE,
    Permission.AGREEMENT_UPDATE,
    Permission.AGREEMENT_GENERATE,
    Permission.AGREEMENT_SIGN,
    Permission.AGREEMENT_FINALIZE,
    Permission.AGREEMENT_CANCEL,
    Permission.AGREEMENT_TEMPLATE_READ,
    Permission.AGREEMENT_TEMPLATE_CREATE,
    Permission.AGREEMENT_TEMPLATE_UPDATE,
    Permission.AGREEMENT_TEMPLATE_ARCHIVE,
    Permission.ELECTRICITY_READ,
    Permission.ELECTRICITY_CREATE,
    Permission.ELECTRICITY_UPDATE,
    Permission.ELECTRICITY_FINALIZE,
    Permission.MEAL_READ,
    Permission.MEAL_CREATE,
    Permission.MEAL_UPDATE,
    Permission.MEAL_MANAGE_SUBSCRIPTIONS,
    Permission.MEAL_RECORD,
    Permission.MEAL_FINALIZE,
    Permission.BILLING_READ,
    Permission.BILLING_CREATE,
    Permission.BILLING_UPDATE,
    Permission.INVOICE_READ,
    Permission.INVOICE_CREATE,
    Permission.INVOICE_UPDATE,
    Permission.INVOICE_ISSUE,
    Permission.INVOICE_VOID,
    Permission.PAYMENT_READ,
    Permission.PAYMENT_CREATE,
    Permission.PAYMENT_ALLOCATE,
    Permission.LEDGER_READ,
    Permission.SECURITY_DEPOSIT_READ,
    Permission.SECURITY_DEPOSIT_UPDATE,
    Permission.MAINTENANCE_READ,
    Permission.MAINTENANCE_CREATE,
    Permission.MAINTENANCE_UPDATE,
    Permission.MAINTENANCE_ASSIGN,
    Permission.MAINTENANCE_COMMENT,
    Permission.MAINTENANCE_COMPLETE,
    Permission.MAINTENANCE_VERIFY,
    Permission.MAINTENANCE_CLOSE,
    Permission.MAINTENANCE_CANCEL,
    Permission.MAINTENANCE_MANAGE_COST,
    Permission.MAINTENANCE_MANAGE_VENDOR,
    Permission.REPORTS_READ,
    Permission.DASHBOARD_READ,
    Permission.NOTIFICATION_READ,
    Permission.NOTIFICATION_CREATE,
    Permission.NOTIFICATION_UPDATE,
    Permission.NOTIFICATION_DELETE,
  ],

  [UserRole.ACCOUNTANT]: [
    Permission.EXPENSE_READ,
    Permission.EXPENSE_CREATE,
    Permission.EXPENSE_UPDATE,
    Permission.INVENTORY_READ,
    Permission.STAFF_READ,
    Permission.ATTENDANCE_READ,
    Permission.VISITOR_READ,
    Permission.ORGANIZATION_READ,
    Permission.TEAM_READ,
    Permission.PROPERTY_READ,
    Permission.TENANT_READ,
    Permission.TENANT_KYC_READ,
    Permission.LEASE_READ,
    Permission.CHECKIN_READ,
    Permission.CHECKOUT_READ,
    Permission.AGREEMENT_READ,
    Permission.AGREEMENT_TEMPLATE_READ,
    Permission.ELECTRICITY_READ,
    Permission.ELECTRICITY_FINALIZE,
    Permission.MEAL_READ,
    Permission.MEAL_FINALIZE,
    Permission.MEAL_MANAGE_SUBSCRIPTIONS,
    Permission.BILLING_READ,
    Permission.BILLING_CREATE,
    Permission.BILLING_UPDATE,
    Permission.INVOICE_READ,
    Permission.INVOICE_CREATE,
    Permission.INVOICE_UPDATE,
    Permission.INVOICE_ISSUE,
    Permission.INVOICE_VOID,
    Permission.PAYMENT_READ,
    Permission.PAYMENT_CREATE,
    Permission.PAYMENT_ALLOCATE,
    Permission.PAYMENT_REFUND,
    Permission.LEDGER_READ,
    Permission.SECURITY_DEPOSIT_READ,
    Permission.SECURITY_DEPOSIT_UPDATE,
    Permission.MAINTENANCE_READ,
    Permission.MAINTENANCE_MANAGE_COST,
    Permission.REPORTS_READ,
    Permission.DASHBOARD_READ,
    Permission.NOTIFICATION_READ,
    Permission.NOTIFICATION_UPDATE,
    Permission.NOTIFICATION_DELETE,
  ],

  [UserRole.WARDEN]: [
    Permission.EXPENSE_READ,
    Permission.EXPENSE_CREATE,
    Permission.INVENTORY_READ,
    Permission.INVENTORY_CREATE,
    Permission.INVENTORY_UPDATE,
    Permission.STAFF_READ,
    Permission.ATTENDANCE_READ,
    Permission.ATTENDANCE_RECORD,
    Permission.VISITOR_READ,
    Permission.VISITOR_CREATE,
    Permission.VISITOR_UPDATE,
    Permission.ORGANIZATION_READ,
    Permission.TEAM_READ,
    Permission.PROPERTY_READ,
    Permission.TENANT_READ,
    Permission.TENANT_UPDATE,
    Permission.TENANT_KYC_READ,
    Permission.TENANT_KYC_UPLOAD,
    Permission.LEASE_READ,
    Permission.LEASE_UPDATE,
    Permission.CHECKIN_READ,
    Permission.CHECKIN_CREATE,
    Permission.CHECKOUT_READ,
    Permission.CHECKOUT_CREATE,
    Permission.AGREEMENT_READ,
    Permission.AGREEMENT_CREATE,
    Permission.AGREEMENT_GENERATE,
    Permission.AGREEMENT_SIGN,
    Permission.ELECTRICITY_READ,
    Permission.ELECTRICITY_CREATE,
    Permission.ELECTRICITY_UPDATE,
    Permission.MEAL_READ,
    Permission.MEAL_CREATE,
    Permission.MEAL_UPDATE,
    Permission.MEAL_MANAGE_SUBSCRIPTIONS,
    Permission.MEAL_RECORD,
    Permission.BILLING_READ,
    Permission.INVOICE_READ,
    Permission.PAYMENT_READ,
    Permission.SECURITY_DEPOSIT_READ,
    Permission.MAINTENANCE_READ,
    Permission.MAINTENANCE_CREATE,
    Permission.MAINTENANCE_UPDATE,
    Permission.MAINTENANCE_COMMENT,
    Permission.DASHBOARD_READ,
    Permission.NOTIFICATION_READ,
    Permission.NOTIFICATION_UPDATE,
    Permission.NOTIFICATION_DELETE,
  ],

  [UserRole.SECURITY]: [
    Permission.STAFF_READ,
    Permission.ATTENDANCE_READ,
    Permission.ATTENDANCE_RECORD,
    Permission.VISITOR_READ,
    Permission.VISITOR_CREATE,
    Permission.VISITOR_UPDATE,
    Permission.ORGANIZATION_READ,
    Permission.PROPERTY_READ,
    Permission.TENANT_READ,
    Permission.LEASE_READ,
    Permission.CHECKIN_READ,
    Permission.CHECKOUT_READ,
    Permission.AGREEMENT_READ,
    Permission.INVOICE_READ,
    Permission.PAYMENT_READ,
    Permission.MAINTENANCE_READ,
    Permission.NOTIFICATION_READ,
    Permission.NOTIFICATION_UPDATE,
    Permission.NOTIFICATION_DELETE,
  ],

  [UserRole.MAINTENANCE_STAFF]: [
    Permission.INVENTORY_READ,
    Permission.INVENTORY_UPDATE,
    Permission.STAFF_READ,
    Permission.ATTENDANCE_READ,
    Permission.VISITOR_READ,
    Permission.ORGANIZATION_READ,
    Permission.PROPERTY_READ,
    Permission.MAINTENANCE_READ,
    Permission.MAINTENANCE_CREATE,
    Permission.MAINTENANCE_UPDATE,
    Permission.MAINTENANCE_COMMENT,
    Permission.MAINTENANCE_COMPLETE,
    Permission.NOTIFICATION_READ,
    Permission.NOTIFICATION_UPDATE,
    Permission.NOTIFICATION_DELETE,
  ],

  [UserRole.TENANT]: [
    Permission.VISITOR_READ,
    Permission.VISITOR_CREATE,
    Permission.VISITOR_UPDATE,
    Permission.PROPERTY_READ,
    Permission.LEASE_READ,
    Permission.AGREEMENT_READ,
    Permission.AGREEMENT_SIGN,
    Permission.ELECTRICITY_READ,
    Permission.MEAL_READ,
    Permission.BILLING_READ,
    Permission.INVOICE_READ,
    Permission.PAYMENT_READ,
    Permission.SECURITY_DEPOSIT_READ,
    Permission.MAINTENANCE_READ,
    Permission.MAINTENANCE_CREATE,
    Permission.MAINTENANCE_COMMENT,
    Permission.NOTIFICATION_READ,
    Permission.NOTIFICATION_UPDATE,
    Permission.NOTIFICATION_DELETE,
  ],
};

/**
 * Checks whether a set of roles satisfies a required permission
 */
export function hasPermission(roles: UserRole[], requiredPermission: Permission): boolean {
  if (!roles || roles.length === 0) return false;
  if (roles.includes(UserRole.OWNER)) return true; // Owner has implicit superuser privileges

  return roles.some((role) => {
    const rolePerms = ROLE_PERMISSIONS_MAP[role];
    return rolePerms ? rolePerms.includes(requiredPermission) : false;
  });
}

/**
 * Checks whether a set of roles satisfies all required permissions
 */
export function hasAllPermissions(roles: UserRole[], requiredPermissions: Permission[]): boolean {
  if (!requiredPermissions || requiredPermissions.length === 0) return true;
  return requiredPermissions.every((perm) => hasPermission(roles, perm));
}

/**
 * Checks whether a set of roles satisfies at least one required permission
 */
export function hasAnyPermission(roles: UserRole[], requiredPermissions: Permission[]): boolean {
  if (!requiredPermissions || requiredPermissions.length === 0) return true;
  return requiredPermissions.some((perm) => hasPermission(roles, perm));
}

/**
 * Standardized Email Normalization Helper (trim whitespace and convert to lowercase)
 */
export function normalizeEmail(email: string): string {
  if (!email) return '';
  return email.trim().toLowerCase();
}
